@echo off
echo Initializing Git...
git init
echo Adding Remote...
git remote add origin https://github.com/sadaru2002/AlphaForge.git
echo Adding Files...
git add .
echo Committing...
git commit -m "Initial commit of AlphaForge (Backend + Frontend)"
echo Pushing...
git push -u origin master
pause
